config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root 'static_pages#index'

  get 'about_us', to: 'static_pages#about_us'

  get 'contact_us', to: 'static_pages#contact_us'

  resources 'tweets'

  resources 'profiles'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
		validates :content, presence: true
		validates :content, length: { maximum: 280}

		belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  has_many :tweets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def show
		@user = User.find(params["id"])
		@tweets = @user.tweets
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


	def index

		@dog = "P Terry"
	end

	def about_us
		@flower = "This is the about us page! 
			We kindly thank you for joining us today!"
	end


	def contact_us
		@birdy = "call us at (414) 216-7002 or 
			email us at Ruby@onrails.com"
	end

	def dumbass
		@dumbass = "dumbass"
	end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

# current_user
before_action :authenticate_user!



def new
	@tweet = Tweet.new
end


def index
	@tweets = Tweet.all
end



def create
	print "rex rex fire fire "
	print params["tweet"]["content"]
	print "cold cold cold cold cold "
	@tweet = Tweet.new
	@tweet.content = params["tweet"]["content"]
	@tweet.user = current_user
	@tweet.save
	if @tweet.save
		redirect_to new_tweet_path
	else
		render 'new', status: 422

		#do something else
end

	# this is the code that will create a new tweet
	# and then go back to the beginning with a 
	# fresh form
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Uat X" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


  </head>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    

        <%= link_to "UAT-X", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">

          <%= link_to "New Tweet", new_tweet_path, class: "nav-link active" %>

        </li>


        <li class="nav-item">

          <%= link_to "Newsfeed", tweets_path, class: "nav-link active" %>

        </li>




        <% if user_signed_in? %>

        <li class="nav-item">


           <%= link_to "My Profile", profile_path(current_user), class: "nav-link active" %>

        <% end %>

      </ul>



      
    <% if user_signed_in? %>

        <%= link_to "Log the Frick Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link active" %>

    <% else %>

      <%= link_to "Sign Up", new_user_registration_path, class: "nav-link active" %>

      &nbsp; &nbsp; &nbsp;

      <%= link_to "Log In", new_user_session_path, class: "nav-link active" %>

    <% end %>

      



    </div>
  </div>
</nav>


<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


  <body>
    <div class="container">
      <%= yield %>
      <%#This yield is all the stuff we code ourselves %>
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

app/views/profiles/show.html.erb
<%= @user.email %>



<% @tweets.each do |tweet| %>



		<div class="card" style="width: 18rem;">
		  <div class="card-body">
		    <h5 class="card-title"><%= tweet.content%> </h5>
		    <h6 class="card-subtitle mb-2 text-body-secondary"><%= time_ago_in_words(tweet.created_at)%></h6>
		  </div>
		</div>

		<br/>


<% end %>

app/views/static_pages/about_us.html.erb
<%= @flower %>

app/views/static_pages/contact_us.html.erb
<%= @birdy %>

app/views/static_pages/dumbass.html.erb
<%= @dumbass %>

app/views/static_pages/index.html.erb
 <div class="px-4 py-5 my-5 text-center">
    
 	<%= image_tag 'fa.jpeg', class: "d-block mx-auto mb-4", style: "max-width: 25%;" %>
  


    <h1 class="display-5 fw-bold text-body-emphasis">Welcome to Freaky Ahh Twitter!</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">This is the only Freaky-Ahh-focused twitter app in the whole wide world!! congrats on finding our fantastic page, we hope you enjoy your time exploring what there is to see in our lovely minds</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">


        <%= link_to tweets_path, class: "nav-link active" do %>
  <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Hell yeah!</button>
<% end %>

        


        <%= link_to tweets_path, class: "nav-link active" do %>
        <button type="button" class="btn btn-outline-secondary btn-lg px-4">Click this if you're stoopid
        </button>
        <% end %>


      </div>
    </div>
  </div>

app/views/tweets/index.html.erb
<% @tweets.each do |tweet| %>



		<div class="card" style="width: 18rem;">
		  <div class="card-body">
		    <h5 class="card-title"><%= tweet.content%> </h5>
		    <h6 class="card-subtitle mb-2 text-body-secondary"><%= time_ago_in_words(tweet.created_at)%></h6>
		    <%= link_to tweet.user.email, profile_path(tweet.user) %>
		  </div>
		</div>

		<br/>


<% end %>

app/views/tweets/new.html.erb
Create your new tweet here (max 280 characters)


<%= simple_form_for @tweet do |f| %>
  <%= f.input :content %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>